### ISSUE TITLE
WorkShop: Material de Apoio

### ISSUE THREAD

**Issue by milesibastos** [nodeschool/rio#9]
Olá Pessoal!
Estou escrevendo um série de _posts_ com a intenção de criar um material de apoio em português para os eventos e gostaria muito do _feedback_ de vocês.

Segue o link:
https://medium.com/devexpert/nodeschool/home

**Comment by danielsouzapinna** [comment]
milesibastos,

Muito boa a iniciativa, vou começar a ler o material e dou feedback em breve!
